eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
server:
    port: 8081
spring:
    application:
        name: service-customer
    data:
        mongodb:
            uri: mongodb://localhost:27017/ms-customer